"""baseline schema

Revision ID: 000baseline0
Revises:
Create Date: 2026-08-20 10:05:00.000000

This is the real root of the migration chain. The original first migration,
a1b2c3d4e5f6, was deliberately NOT a baseline -- its own docstring says so
outright: "create_all() already owns table creation for anything missing."
Every migration since then only ever ALTERs or adds new tables on top of
that assumption -- none of them can create the schema from nothing.

That assumption broke today: Base.metadata.create_all(bind=engine) was
removed from app/main.py (2026-08-20), since it had been silently fighting
Alembic -- most recently by creating breathquest_refresh_tokens itself,
before the real migration for it ever ran, causing a DuplicateTable error.
Without create_all(), `alembic upgrade head` is now the ONLY way a fresh
database gets its schema, so a real baseline is required.

Generated by diffing an empty Postgres database directly against
Base.metadata (all 9 files in app/models/, imported explicitly -- see
backend/gen_baseline.py, not committed) via alembic.autogenerate's
produce_migrations(), rather than the `alembic revision --autogenerate`
CLI, which refused to generate a rootless revision against this repo's
existing multi-head chain even with --head base --splice.

Do NOT run this against a database that already has these tables --
it will fail with DuplicateTable, exactly like breathquest_refresh_tokens
did. For an existing (already-migrated) database, stamp this revision
instead of running it:
    alembic stamp 000baseline0
For a genuinely fresh database, `alembic upgrade head` now works end to
end starting from this revision.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '000baseline0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = set(inspector.get_table_names())

    from sqlalchemy.dialects.postgresql import ENUM
    _orig_enum_create = ENUM.create
    ENUM.create = lambda self, bind=None, checkfirst=True: _orig_enum_create(self, bind=bind, checkfirst=True)

    if 'assessment_words' not in existing_tables:
        op.create_table('assessment_words',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('word', sa.String(length=120), nullable=False),
        sa.Column('image_prompt', sa.String(length=240), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
        sa.Column('animation_prompt', sa.String(length=500), nullable=True),
        sa.Column('animation_filename', sa.String(length=240), nullable=True),
        sa.Column('display_order', sa.Integer(), nullable=False),
        sa.Column('media_filename', sa.String(length=240), nullable=True),
        sa.Column('word_key', sa.String(length=120), nullable=True),
        sa.Column('english', sa.String(length=120), nullable=True),
        sa.Column('telugu', sa.String(length=120), nullable=True),
        sa.Column('hindi', sa.String(length=120), nullable=True),
        sa.Column('tamil', sa.String(length=120), nullable=True),
        sa.Column('kannada', sa.String(length=120), nullable=True),
        sa.Column('malayalam', sa.String(length=120), nullable=True),
        sa.Column('bengali', sa.String(length=120), nullable=True),
        sa.Column('marathi', sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_assessment_words_id'), 'assessment_words', ['id'], unique=False)
        op.create_index(op.f('ix_assessment_words_word'), 'assessment_words', ['word'], unique=True)
        op.create_index(op.f('ix_assessment_words_word_key'), 'assessment_words', ['word_key'], unique=False)

    if 'breathquest_email_verifications' not in existing_tables:
        op.create_table('breathquest_email_verifications',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('otp_code_hash', sa.String(length=64), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('attempts', sa.Integer(), nullable=False),
        sa.Column('verified', sa.Boolean(), nullable=False),
        sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_breathquest_email_verifications_email'), 'breathquest_email_verifications', ['email'], unique=False)

    if 'breathquest_kid_login_throttle' not in existing_tables:
        op.create_table('breathquest_kid_login_throttle',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('identifier', sa.String(length=255), nullable=False),
        sa.Column('failed_attempts', sa.Integer(), nullable=False),
        sa.Column('first_failed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_failed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_breathquest_kid_login_throttle_identifier'), 'breathquest_kid_login_throttle', ['identifier'], unique=True)

    if 'breathquest_phone_verifications' not in existing_tables:
        op.create_table('breathquest_phone_verifications',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('phone', sa.String(length=32), nullable=False),
        sa.Column('otp_code_hash', sa.String(length=64), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('attempts', sa.Integer(), nullable=False),
        sa.Column('verified', sa.Boolean(), nullable=False),
        sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_breathquest_phone_verifications_phone'), 'breathquest_phone_verifications', ['phone'], unique=False)

    if 'breathquest_refresh_tokens' not in existing_tables:
        op.create_table('breathquest_refresh_tokens',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('token_hash', sa.String(length=64), nullable=False),
        sa.Column('owner_kind', sa.String(length=16), nullable=False),
        sa.Column('owner_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_breathquest_refresh_tokens_owner_id'), 'breathquest_refresh_tokens', ['owner_id'], unique=False)
        op.create_index(op.f('ix_breathquest_refresh_tokens_token_hash'), 'breathquest_refresh_tokens', ['token_hash'], unique=False)

    if 'breathquest_retrain_checkpoints' not in existing_tables:
        op.create_table('breathquest_retrain_checkpoints',
        sa.Column('scope', sa.String(), nullable=False),
        sa.Column('last_retrained_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('event_count_at_checkpoint', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('scope')
        )

    if 'breathquest_therapists' not in existing_tables:
        op.create_table('breathquest_therapists',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('clinic_name', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_breathquest_therapists_email'), 'breathquest_therapists', ['email'], unique=False)

    if 'exercise_templates' not in existing_tables:
        op.create_table('exercise_templates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=160), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('duration_label', sa.String(length=32), nullable=False),
        sa.Column('target_categories', sa.ARRAY(sa.String()), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )

    if 'therapists' not in existing_tables:
        op.create_table('therapists',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('full_name', sa.String(), nullable=False),
        sa.Column('clinic_name', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_therapists_email'), 'therapists', ['email'], unique=True)

    if 'vaakmirror_sessions' not in existing_tables:
        op.create_table('vaakmirror_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('patient_id', sa.String(), nullable=False),
        sa.Column('game', sa.Enum('mirror_mirror', 'tongue_tamer', 'lip_sync_hero', name='gamename'), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_vaakmirror_sessions_patient_id'), 'vaakmirror_sessions', ['patient_id'], unique=False)

    if 'attempts' not in existing_tables:
        op.create_table('attempts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('sound_id', sa.String(length=16), nullable=True),
        sa.Column('place', sa.String(length=32), nullable=True),
        sa.Column('manner', sa.String(length=32), nullable=True),
        sa.Column('voicing', sa.String(length=16), nullable=True),
        sa.Column('outcome', sa.Enum('passed', 'caught', 'missed', name='attemptoutcome'), nullable=False),
        sa.Column('score', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], ['vaakmirror_sessions.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if 'exercise_assignments' not in existing_tables:
        op.create_table('exercise_assignments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('patient_id', sa.String(), nullable=False),
        sa.Column('exercise_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('not_started', 'assigned', 'in_progress', 'completed', name='assignmentstatus'), nullable=False),
        sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['exercise_id'], ['exercise_templates.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_exercise_assignments_patient_id'), 'exercise_assignments', ['patient_id'], unique=False)

    if 'patients' not in existing_tables:
        op.create_table('patients',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('age', sa.Integer(), nullable=True),
        sa.Column('date_of_birth', sa.String(), nullable=True),
        sa.Column('language', sa.String(), nullable=True),
        sa.Column('gender', sa.String(), nullable=True),
        sa.Column('diagnosis', sa.String(), nullable=True),
        sa.Column('therapist_name', sa.String(), nullable=True),
        sa.Column('registered_therapist_id', sa.UUID(), nullable=True),
        sa.Column('parent_name', sa.String(), nullable=True),
        sa.Column('parent_contact', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['registered_therapist_id'], ['therapists.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_patients_registered_therapist_id'), 'patients', ['registered_therapist_id'], unique=False)

    if 'breathquest_patients' not in existing_tables:
        op.create_table('breathquest_patients',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('therapist_id', sa.UUID(), nullable=True),
        sa.Column('first_name', sa.String(length=100), nullable=False),
        sa.Column('avatar', sa.String(length=50), nullable=False),
        sa.Column('avatar_photo_url', sa.String(length=255), nullable=True),
        sa.Column('pin_hash', sa.String(length=64), nullable=False),
        sa.Column('player_code', sa.String(length=10), nullable=False),
        sa.Column('age', sa.Integer(), nullable=True),
        sa.Column('diagnosis_notes', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('assessment_patient_id', sa.UUID(), nullable=True),
        sa.Column('assessment_completed', sa.Boolean(), nullable=False),
        sa.Column('assessment_summary', sa.JSON(), nullable=True),
        sa.Column('parent_email', sa.String(length=255), nullable=True),
        sa.Column('parent_consent_verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('parent_phone', sa.String(length=32), nullable=True),
        sa.Column('parent_phone_consent_verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['assessment_patient_id'], ['patients.id'], ),
        sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_breathquest_patients_assessment_patient_id'), 'breathquest_patients', ['assessment_patient_id'], unique=False)
        op.create_index(op.f('ix_breathquest_patients_player_code'), 'breathquest_patients', ['player_code'], unique=True)
        op.create_index(op.f('ix_breathquest_patients_therapist_id'), 'breathquest_patients', ['therapist_id'], unique=False)

    if 'sessions' not in existing_tables:
        op.create_table('sessions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('patient_id', sa.UUID(), nullable=True),
        sa.Column('f0_mean', sa.Float(), nullable=True),
        sa.Column('mpt', sa.Float(), nullable=True),
        sa.Column('jitter', sa.Float(), nullable=True),
        sa.Column('shimmer', sa.Float(), nullable=True),
        sa.Column('hnr', sa.Float(), nullable=True),
        sa.Column('target_word', sa.String(), nullable=True),
        sa.Column('spoken_word', sa.String(), nullable=True),
        sa.Column('accuracy', sa.Integer(), nullable=True),
        sa.Column('feedback', sa.String(), nullable=True),
        sa.Column('stars', sa.Integer(), nullable=True),
        sa.Column('audio_file', sa.String(), nullable=True),
        sa.Column('session_type', sa.String(), nullable=True),
        sa.Column('trs_score', sa.Integer(), nullable=True),
        sa.Column('severity_classification', sa.String(), nullable=True),
        sa.Column('error_patterns', postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column('targeted_quests', postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column('diagnostic_report', sa.String(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if 'breathquest_assignments' not in existing_tables:
        op.create_table('breathquest_assignments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('patient_id', sa.UUID(), nullable=False),
        sa.Column('assigned_by', sa.UUID(), nullable=False),
        sa.Column('game', sa.String(length=50), nullable=False),
        sa.Column('level_id', sa.String(length=50), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('instructions', sa.Text(), nullable=True),
        sa.Column('status', sa.Enum('assigned', 'in_progress', 'completed', 'overdue', name='assignmentstatus'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['assigned_by'], ['therapists.id'], ),
        sa.ForeignKeyConstraint(['patient_id'], ['breathquest_patients.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_breathquest_assignments_patient_id'), 'breathquest_assignments', ['patient_id'], unique=False)

    if 'breathquest_game_sessions' not in existing_tables:
        op.create_table('breathquest_game_sessions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('patient_id', sa.UUID(), nullable=False),
        sa.Column('level_id', sa.Enum('pinwheel', 'float_rider', 'candle', 'balloon', 'dandelion', 'dragon', name='levelid'), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('duration_seconds', sa.Float(), nullable=True),
        sa.Column('status', sa.Enum('in_progress', 'completed', 'abandoned', name='sessionstatus'), nullable=False),
        sa.Column('stars_earned', sa.Integer(), nullable=True),
        sa.Column('completed', sa.Boolean(), nullable=False),
        sa.Column('completion_message', sa.String(length=255), nullable=True),
        sa.Column('avg_breath_strength', sa.Float(), nullable=True),
        sa.Column('max_breath_strength', sa.Float(), nullable=True),
        sa.Column('breath_consistency', sa.Float(), nullable=True),
        sa.Column('total_puffs', sa.Integer(), nullable=True),
        sa.Column('lives_lost', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['patient_id'], ['breathquest_patients.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_breathquest_game_sessions_patient_id'), 'breathquest_game_sessions', ['patient_id'], unique=False)

    if 'breathquest_goals' not in existing_tables:
        op.create_table('breathquest_goals',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('patient_id', sa.UUID(), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('target_metric', sa.String(length=100), nullable=False),
        sa.Column('target_value', sa.Float(), nullable=False),
        sa.Column('baseline_value', sa.Float(), nullable=True),
        sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('achieved', sa.Boolean(), nullable=False),
        sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['therapists.id'], ),
        sa.ForeignKeyConstraint(['patient_id'], ['breathquest_patients.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_breathquest_goals_patient_id'), 'breathquest_goals', ['patient_id'], unique=False)

    if 'breathquest_home_practice_logs' not in existing_tables:
        op.create_table('breathquest_home_practice_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('patient_id', sa.UUID(), nullable=False),
        sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('practiced_on', sa.DateTime(timezone=True), nullable=False),
        sa.Column('duration_minutes', sa.Integer(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['patient_id'], ['breathquest_patients.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_breathquest_home_practice_logs_patient_id'), 'breathquest_home_practice_logs', ['patient_id'], unique=False)

    if 'breathquest_messages' not in existing_tables:
        op.create_table('breathquest_messages',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('patient_id', sa.UUID(), nullable=False),
        sa.Column('sender_role', sa.Enum('therapist', 'parent', name='senderrole'), nullable=False),
        sa.Column('sender_id', sa.UUID(), nullable=True),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['patient_id'], ['breathquest_patients.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_breathquest_messages_patient_id'), 'breathquest_messages', ['patient_id'], unique=False)

    if 'breathquest_parents' not in existing_tables:
        op.create_table('breathquest_parents',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('patient_id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('full_name', sa.String(length=255), nullable=True),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['patient_id'], ['breathquest_patients.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('patient_id')
        )

    if 'breathquest_rl_training_events' not in existing_tables:
        op.create_table('breathquest_rl_training_events',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('child_id', sa.UUID(), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('level_id', sa.String(), nullable=False),
        sa.Column('attempt_number', sa.Integer(), nullable=False),
        sa.Column('score', sa.Float(), nullable=False),
        sa.Column('is_valid_attempt', sa.Boolean(), nullable=False),
        sa.Column('threshold_at_time', sa.Float(), nullable=True),
        sa.Column('action', sa.String(), nullable=True),
        sa.Column('quit_flag', sa.Boolean(), nullable=False),
        sa.Column('raw_features', sa.JSON(), nullable=True),
        sa.Column('severity_numeric', sa.Float(), nullable=False),
        sa.Column('is_targeted_sound', sa.Boolean(), nullable=False),
        sa.Column('policy_used', sa.String(), nullable=True),
        sa.Column('downgrade_reason', sa.String(), nullable=True),
        sa.Column('recommended_action', sa.String(), nullable=True),
        sa.Column('recommendation_message', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['child_id'], ['breathquest_patients.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_breathquest_rl_training_events_child_id'), 'breathquest_rl_training_events', ['child_id'], unique=False)
        op.create_index(op.f('ix_breathquest_rl_training_events_timestamp'), 'breathquest_rl_training_events', ['timestamp'], unique=False)

    if 'breathquest_voicehurdlerace_sessions' not in existing_tables:
        op.create_table('breathquest_voicehurdlerace_sessions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('patient_id', sa.UUID(), nullable=False),
        sa.Column('level_id', sa.Integer(), nullable=False),
        sa.Column('level_name', sa.String(length=100), nullable=False),
        sa.Column('score', sa.Integer(), nullable=False),
        sa.Column('time_remaining', sa.Float(), nullable=False),
        sa.Column('pitch_accuracy', sa.Float(), nullable=False),
        sa.Column('loudness_accuracy', sa.Float(), nullable=False),
        sa.Column('stars', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['patient_id'], ['breathquest_patients.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_breathquest_voicehurdlerace_sessions_patient_id'), 'breathquest_voicehurdlerace_sessions', ['patient_id'], unique=False)

    if 'flashcard_attempts' not in existing_tables:
        op.create_table('flashcard_attempts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('patient_id', sa.UUID(), nullable=False),
        sa.Column('session_id', sa.String(length=64), nullable=False),
        sa.Column('theme_id', sa.String(length=50), nullable=True),
        sa.Column('target_word', sa.String(length=100), nullable=False),
        sa.Column('character', sa.String(length=50), nullable=True),
        sa.Column('language', sa.String(length=20), nullable=False),
        sa.Column('transcript', sa.String(length=255), nullable=True),
        sa.Column('phoneme_matches', sa.JSON(), nullable=False),
        sa.Column('accuracy', sa.Float(), nullable=False),
        sa.Column('composite_score', sa.Float(), nullable=False),
        sa.Column('attempt_number', sa.Integer(), nullable=False),
        sa.Column('repeat_needed', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['patient_id'], ['breathquest_patients.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_flashcard_attempts_created_at'), 'flashcard_attempts', ['created_at'], unique=False)
        op.create_index(op.f('ix_flashcard_attempts_patient_id'), 'flashcard_attempts', ['patient_id'], unique=False)
        op.create_index(op.f('ix_flashcard_attempts_session_id'), 'flashcard_attempts', ['session_id'], unique=False)
        op.create_index(op.f('ix_flashcard_attempts_target_word'), 'flashcard_attempts', ['target_word'], unique=False)
        op.create_index(op.f('ix_flashcard_attempts_theme_id'), 'flashcard_attempts', ['theme_id'], unique=False)

    if 'flashcard_phoneme_mastery' not in existing_tables:
        op.create_table('flashcard_phoneme_mastery',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('patient_id', sa.UUID(), nullable=False),
        sa.Column('phoneme', sa.String(length=10), nullable=False),
        sa.Column('attempts_count', sa.Integer(), nullable=False),
        sa.Column('correct_count', sa.Integer(), nullable=False),
        sa.Column('accuracy', sa.Float(), nullable=False),
        sa.Column('last_word', sa.String(length=100), nullable=True),
        sa.Column('first_practiced_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['patient_id'], ['breathquest_patients.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('patient_id', 'phoneme', name='uq_patient_phoneme')
        )
        op.create_index(op.f('ix_flashcard_phoneme_mastery_patient_id'), 'flashcard_phoneme_mastery', ['patient_id'], unique=False)
        op.create_index(op.f('ix_flashcard_phoneme_mastery_phoneme'), 'flashcard_phoneme_mastery', ['phoneme'], unique=False)

    if 'breathquest_session_events' not in existing_tables:
        op.create_table('breathquest_session_events',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('session_id', sa.UUID(), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('breath_value', sa.Float(), nullable=True),
        sa.Column('event_data', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], ['breathquest_game_sessions.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_breathquest_session_events_session_id'), 'breathquest_session_events', ['session_id'], unique=False)

    if 'breathquest_subscriptions' not in existing_tables:
        op.create_table('breathquest_subscriptions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('owner_parent_id', sa.UUID(), nullable=True),
        sa.Column('owner_therapist_id', sa.UUID(), nullable=True),
        sa.Column('plan_type', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
        sa.Column('provider', sa.String(length=30), nullable=True),
        sa.Column('provider_customer_id', sa.String(length=255), nullable=True),
        sa.Column('provider_subscription_id', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['owner_parent_id'], ['breathquest_parents.id'], ),
        sa.ForeignKeyConstraint(['owner_therapist_id'], ['therapists.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_breathquest_subscriptions_owner_parent_id'), 'breathquest_subscriptions', ['owner_parent_id'], unique=True)
        op.create_index(op.f('ix_breathquest_subscriptions_owner_therapist_id'), 'breathquest_subscriptions', ['owner_therapist_id'], unique=True)

    if 'breathquest_therapist_notes' not in existing_tables:
        op.create_table('breathquest_therapist_notes',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('patient_id', sa.UUID(), nullable=False),
        sa.Column('therapist_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('session_id', sa.UUID(), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['patient_id'], ['breathquest_patients.id'], ),
        sa.ForeignKeyConstraint(['session_id'], ['breathquest_game_sessions.id'], ),
        sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_breathquest_therapist_notes_patient_id'), 'breathquest_therapist_notes', ['patient_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_breathquest_therapist_notes_patient_id'), table_name='breathquest_therapist_notes')
    op.drop_table('breathquest_therapist_notes')
    op.drop_index(op.f('ix_breathquest_subscriptions_owner_therapist_id'), table_name='breathquest_subscriptions')
    op.drop_index(op.f('ix_breathquest_subscriptions_owner_parent_id'), table_name='breathquest_subscriptions')
    op.drop_table('breathquest_subscriptions')
    op.drop_index(op.f('ix_breathquest_session_events_session_id'), table_name='breathquest_session_events')
    op.drop_table('breathquest_session_events')
    op.drop_index(op.f('ix_flashcard_phoneme_mastery_phoneme'), table_name='flashcard_phoneme_mastery')
    op.drop_index(op.f('ix_flashcard_phoneme_mastery_patient_id'), table_name='flashcard_phoneme_mastery')
    op.drop_table('flashcard_phoneme_mastery')
    op.drop_index(op.f('ix_flashcard_attempts_theme_id'), table_name='flashcard_attempts')
    op.drop_index(op.f('ix_flashcard_attempts_target_word'), table_name='flashcard_attempts')
    op.drop_index(op.f('ix_flashcard_attempts_session_id'), table_name='flashcard_attempts')
    op.drop_index(op.f('ix_flashcard_attempts_patient_id'), table_name='flashcard_attempts')
    op.drop_index(op.f('ix_flashcard_attempts_created_at'), table_name='flashcard_attempts')
    op.drop_table('flashcard_attempts')
    op.drop_index(op.f('ix_breathquest_voicehurdlerace_sessions_patient_id'), table_name='breathquest_voicehurdlerace_sessions')
    op.drop_table('breathquest_voicehurdlerace_sessions')
    op.drop_index(op.f('ix_breathquest_rl_training_events_timestamp'), table_name='breathquest_rl_training_events')
    op.drop_index(op.f('ix_breathquest_rl_training_events_child_id'), table_name='breathquest_rl_training_events')
    op.drop_table('breathquest_rl_training_events')
    op.drop_table('breathquest_parents')
    op.drop_index(op.f('ix_breathquest_messages_patient_id'), table_name='breathquest_messages')
    op.drop_table('breathquest_messages')
    op.drop_index(op.f('ix_breathquest_home_practice_logs_patient_id'), table_name='breathquest_home_practice_logs')
    op.drop_table('breathquest_home_practice_logs')
    op.drop_index(op.f('ix_breathquest_goals_patient_id'), table_name='breathquest_goals')
    op.drop_table('breathquest_goals')
    op.drop_index(op.f('ix_breathquest_game_sessions_patient_id'), table_name='breathquest_game_sessions')
    op.drop_table('breathquest_game_sessions')
    op.drop_index(op.f('ix_breathquest_assignments_patient_id'), table_name='breathquest_assignments')
    op.drop_table('breathquest_assignments')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_breathquest_patients_therapist_id'), table_name='breathquest_patients')
    op.drop_index(op.f('ix_breathquest_patients_player_code'), table_name='breathquest_patients')
    op.drop_index(op.f('ix_breathquest_patients_assessment_patient_id'), table_name='breathquest_patients')
    op.drop_table('breathquest_patients')
    op.drop_index(op.f('ix_patients_registered_therapist_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_exercise_assignments_patient_id'), table_name='exercise_assignments')
    op.drop_table('exercise_assignments')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_vaakmirror_sessions_patient_id'), table_name='vaakmirror_sessions')
    op.drop_table('vaakmirror_sessions')
    op.drop_index(op.f('ix_therapists_email'), table_name='therapists')
    op.drop_table('therapists')
    op.drop_table('exercise_templates')
    op.drop_index(op.f('ix_breathquest_therapists_email'), table_name='breathquest_therapists')
    op.drop_table('breathquest_therapists')
    op.drop_table('breathquest_retrain_checkpoints')
    op.drop_index(op.f('ix_breathquest_refresh_tokens_token_hash'), table_name='breathquest_refresh_tokens')
    op.drop_index(op.f('ix_breathquest_refresh_tokens_owner_id'), table_name='breathquest_refresh_tokens')
    op.drop_table('breathquest_refresh_tokens')
    op.drop_index(op.f('ix_breathquest_phone_verifications_phone'), table_name='breathquest_phone_verifications')
    op.drop_table('breathquest_phone_verifications')
    op.drop_index(op.f('ix_breathquest_kid_login_throttle_identifier'), table_name='breathquest_kid_login_throttle')
    op.drop_table('breathquest_kid_login_throttle')
    op.drop_index(op.f('ix_breathquest_email_verifications_email'), table_name='breathquest_email_verifications')
    op.drop_table('breathquest_email_verifications')
    op.drop_index(op.f('ix_assessment_words_word_key'), table_name='assessment_words')
    op.drop_index(op.f('ix_assessment_words_word'), table_name='assessment_words')
    op.drop_index(op.f('ix_assessment_words_id'), table_name='assessment_words')
    op.drop_table('assessment_words')
