"""add refresh tokens table

Revision ID: 2f831c351e22
Revises: a9f3c7d2e1b4
Create Date: 2026-08-20 09:29:20.786784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f831c351e22'
down_revision: Union[str, Sequence[str], None] = 'a9f3c7d2e1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written -- the autogenerated version also tried to drop a dozen
    # unrelated tables (messages, game_settings, goals, parents,
    # retrain_checkpoints, rl_training_events, voicehurdlerace_sessions,
    # email_verifications, subscriptions, assignments, ...) because the
    # live DB has drifted from what the ORM models declare. That drift is
    # real but it's a separate problem -- this migration touches only the
    # new breathquest_refresh_tokens table, nothing else.
    op.create_table(
        'breathquest_refresh_tokens',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('token_hash', sa.String(length=64), nullable=False),
        sa.Column('owner_kind', sa.String(length=16), nullable=False),
        sa.Column('owner_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_breathquest_refresh_tokens_owner_id'),
        'breathquest_refresh_tokens', ['owner_id'], unique=False,
    )
    op.create_index(
        op.f('ix_breathquest_refresh_tokens_token_hash'),
        'breathquest_refresh_tokens', ['token_hash'], unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_breathquest_refresh_tokens_token_hash'), table_name='breathquest_refresh_tokens')
    op.drop_index(op.f('ix_breathquest_refresh_tokens_owner_id'), table_name='breathquest_refresh_tokens')
    op.drop_table('breathquest_refresh_tokens')
