"""add assessment_completed/assessment_summary to breathquest_patients

Revision ID: a1b2c3d4e5f6
Revises:
Create Date: 2026-08-12

This is the first Alembic migration in this project. It is deliberately
NOT a full baseline of the existing schema -- create_all() already owns
table creation for anything missing, and every table already exists in
deployed environments. This migration only covers the one thing
create_all() genuinely can't do: altering an EXISTING table.

Hand-written, not autogenerated -- there's no live DB in the sandbox
this was authored in to diff against, so this was written by reading
the model directly (backend/app/models/breathquest_models.py) rather
than via `alembic revision --autogenerate`. Double check with
`alembic check` (or a diff against a real DB) before relying on
autogenerate for the *next* migration after this one.

assessment_completed is added with server_default=false specifically
because it's NOT NULL. Without a server-side default, ADD COLUMN on a
table that already has rows fails outright on Postgres -- the model's
`default=False` is a Python/ORM-side default only, applied by
SQLAlchemy on INSERT, and never helps existing rows or non-ORM writes.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a1b2c3d4e5f6"
down_revision = '000baseline0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "breathquest_patients",
        sa.Column(
            "assessment_completed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column(
        "breathquest_patients",
        sa.Column("assessment_summary", sa.JSON(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("breathquest_patients", "assessment_summary")
    op.drop_column("breathquest_patients", "assessment_completed")
